# baseurl: /infopoetry

collections:
  infopoetries:
    output: true
    permalink: /:collection/:name
  mediums:

defaults:
  - scope:
      path: ""
      type: "infopoetries"
    values:
      layout: "infopoetry"
  - scope:
      path: ""
    values:
      layout: "default"
