backend:
  name: github
  repo: densitydesign/infopoetry-website

media_folder: "assets/images/uploads"

collections:
  - label: "Press releases"
    name: "release"
    description: "Add here all the links of the Press Release."
    delete: false
    editor:
      preview: false
    files:
      - label: "Press links"
        name: "press"
        file: "_data/press.yml"
        fields:
          - label: "Press Links"
            name: "links"
            widget: "list"
            fields:
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Year", name: "year", hint: "format must be YYYY, e.g. 2019", widget: "string"}

  - label: "Topics"
    name: "topics"
    label_singular: "Topic"
    description: "This is the list of topics used to categorize the infopoetries. If a new one should appear, add it here."
    editor:
      preview: false
    folder: "_topics"
    extension: "yml"
    create: true
    fields:
      - {label: "Topic name", name: "title", widget: "string"}

  - label: "Mediums"
    name: "mediums"
    label_singular: "Medium"
    description: "This is the list of mediums used to build the infopoetries. If a new one should appear, add it here."
    editor:
      preview: false
    folder: "_mediums"
    extension: "yml"
    create: true
    fields:
      - {label: "Medium name", name: "title", widget: "string"}

  - label: "Institutes"
    name: "institutes"
    label_singular: "Institute"
    description: "This is the list of institutes from which the infopoetries come from. If a new one should appear, add it here"
    editor:
      preview: false
    folder: "_institutes"
    extension: "yml"
    create: true
    fields:
      - {label: "Institute name", name: "title", widget: "string"}

  - label: "Infopoetries"
    name: "infopoetries"
    label_singular: "Infopoetry"
    folder: "_infopoetries"
    extension: "md"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Description", name: "body", hint: "try to put no more than 300 characters", widget: "text"}
      - {label: "Year", name: "year", hint: "must be an academic year, e.g. 2018-2019", widget: "string"}
      - {label: "Topic", name: "topic", hint: "must be a valid entry from the Topics collection. If you can't find the right one, go to the Topics section in the CMS and add it", widget: "relation", collection: "topics", searchFields: ["title"], valueField: "title"}
      - {label: "Medium", name: "medium", hint: "must be a valid entry from the Mediums collection. If you can't find the right one, go to the Mediums section in the CMS and add it", widget: "relation", collection: "mediums", searchFields: ["title"], valueField: "title"}
      - {label: "Is Interactive", name: "interactive", widget: "boolean", default: false}
      - {label: "Material", name: "material", widget: "string", hint: "insert only if medium is an object or a particular kind of poster", required: false}
      - {label: "Size", name: "size", widget: "string", hint: "insert only if medium is an object or a particular kind of poster", required: false}
      - {label: "Institute", name: "institute", hint: "must be a valid entry from the Institutes collection. If you can't find the right one, go to the Insitutes section in the CMS and add it", widget: "relation", collection: "institutes", searchFields: ["title"], valueField: "title"}
      - {label: "Featured image", name: "featured", widget: "image", allow_multiple: false}
      - label: "Other images"
        name: "images"
        widget: "list"
        required: false
        field: {label: "Image", name: "image", widget: image, required: false}
      - {label: "Video", name: "video", widget: "file", allow_multiple: false, required: false}
      - label: "Source of the data"
        name: "source"
        widget: "object"
        required: false
        fields:
          - {label: "Source Name", name: "name", widget: "string"}
          - {label: "Source Link", name: "link", widget: "string", required: false}
      - {label: "Metaphor used", name: "methaphor", widget: "text", required: false}
      - {label: "Intended meaning", name: "meaning", widget: "text", required: false}