backend:
  name: github
  repo: densitydesign/infopoetry-website

media_folder: "assets/images/uploads"

collections:
  - label: "Press releases"
    name: "release"
    description: "Add here all the links of the Press Release."
    delete: false
    editor:
      preview: false
    files:
      - label: "Press links"
        name: "press"
        file: "_data/press.yml"
        fields:
          - label: "Press Links"
            name: "links"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}

  - label: "Topics"
    name: "topics"
    label_singular: "Topic"
    description: "This is the list of topics used to categorize the infopoetries. If a new one should appear, add it here."
    editor:
      preview: false
    folder: "_topics"
    extension: "yml"
    create: true
    fields:
      - {label: "Topic name", name: "title", widget: "string"}

  - label: "Mediums"
    name: "mediums"
    label_singular: "Medium"
    description: "This is the list of mediums used to build the infopoetries. If a new one should appear, add it here."
    editor:
      preview: false
    folder: "_mediums"
    extension: "yml"
    create: true
    fields:
      - {label: "Medium name", name: "title", widget: "string"}

  - label: "Institutes"
    name: "institutes"
    label_singular: "Institute"
    description: "This is the list of institutes from which the infopoetries come from. If a new one should appear, add it here"
    editor:
      preview: false
    folder: "_institutes"
    extension: "yml"
    create: true
    fields:
      - {label: "Institute name", name: "title", widget: "string"}

  - label: "Infopoetries"
    name: "infopoetries"
    label_singular: "Infopoetry"
    folder: "_infopoetries"
    extension: "md"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Description", name: "body", hint: "try to put no more than 300 characters", widget: "text"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Topic", name: "topic", hint: "Must be a valid entry from the Topics collection", widget: "relation", collection: "topics", searchFields: ["title"], valueField: "title"}
      - {label: "Medium", name: "medium", hint: "Must be a valid entry from the Mediums collection", widget: "relation", collection: "mediums", searchFields: ["title"], valueField: "title"}
      - {label: "Is Interactive", name: "interactive", widget: "boolean"}
      - {label: "Institute", name: "institute", hint: "Must be a valid entry from the Institutes collection", widget: "relation", collection: "institutes", searchFields: ["title"], valueField: "title"}
      - {label: "Featured image", name: "featured", widget: "image", allow_multiple: false}
      - {label: "Other images", name: "images", widget: "image"}