backend:
  name: github
  repo: densitydesign/infopoetry-website

media_folder: "assets/images/uploads"

collections:
  - label: "Press releases"
    name: "release"
    files:
      - label: "Press links"
        name: "press"
        file: "_data/press.yml"
        fields:
          - label: "Press Links"
            name: "links"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
  - label: "Topics"
    name: "topics"
    files:
      - label: "Topics list"
        name: "topics-list"
        file: "_data/topics.yml"
        fields:
          - label: "Topics"
            name: "list"
            widget: "list"
            fields:
              - {label: "Topic name", name: "title", widget: "string"}
  - label: "Mediums"
    name: "mediums"
    files:
      - label: "Mediums list"
        name: "mediums-list"
        file: "_data/mediums.yml"
        fields:
          - label: "Mediums"
            name: "list"
            widget: "list"
            fields:
              - {label: "Medium name", name: "title", widget: "string"}
  - label: "Institutes"
    name: "institutes"
    files:
      - label: "Institutes list"
        name: "institutes-list"
        file: "_data/institutes.yml"
        fields:
          - label: "Institutes"
            name: "list"
            widget: "list"
            fields:
              - {label: "Institute name", name: "title", widget: "string"}
  - label: "Infopoetries"
    name: "infopoetries"
    folder: "_infopoetries"
    extension: "md"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Description", name: "body", hint: "try to put no more than 300 characters", widget: "text"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Topic", name: "topic", hint: "Must be a valid entry from the Topics collection", widget: "relation", collection: "topics", searchFields: ["title"], valueField: "title"}
      - {label: "Medium", name: "medium", hint: "Must be a valid entry from the Mediums collection", widget: "relation", collection: "mediums", searchFields: ["title"], valueField: "title"}
      - {label: "Institute", name: "institute", hint: "Must be a valid entry from the Institutes collection", widget: "relation", collection: "institutes", searchFields: ["title"], valueField: "title"}
      - {label: "Featured image", name: "featured", widget: "image", allow_multiple: false}
      - {label: "Other images", name: "images", widget: "image"}